services:
  vish:
    image: python:3.12-slim
    container_name: vish
    ports:
      - "8050:8050"
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             python app.py"
